# Shark Attack Data - Cleaning & Analysis

## Business Case
**The Problem:** Since the release of Jaws in 1975, sharks have been widely feared and misunderstood. In reality, only a small fraction of shark species pose any risk to humans, while sharks play a vital role in maintaining healthy ocean ecosystems.

**Our Goal:** Analysing the Global incident log of shark attacks and show that the likelihood of a fatality increases only when the shark is provoked.

**Key Questions We Answer:**
1. What proportion of shark incidents are unprovoked vs. provoked?
2. What are the types of the incidents?
3. How many incidents are actually fatal?
4. Which species are involved — and are they truly dangerous?
5. Which species appear in fatal vs. non-fatal cases?
6. Has the number of incidents increased over time — and if so, why?
7. Does gender play a role in shark incident patterns?
8. What are the types of the incidents?

**Scope:** USA only (largest dataset with most reliable records)

**The Story:** Sharks are not the mindless killers the media portrays. The data shows that most encounters are non-fatal, some are provoked by humans, and the species most often involved rarely cause serious harm. The rise in incidents over time reflects human enterance into shark habitat is not increasing shark aggression.

In [1]:
import numpy as np
import pandas as pd

# Load Shark Attack Dataset
shark_df = pd.read_excel("GSAF5.xls")

In [2]:
#Looking at the data
shark_df.head()

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,24th May,2026.0,Unprovoked,Australia,Queensland,Kennedy Shoal,Spearfishing,Michael Jensz,M,39,...,Undetermined Bull shark most likely,Simon de Marchi: 9 News: 7 News: ABC News:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,17th May,2026.0,Questionable,USA,Maryland,Assateague State Park,Surfing,Brendan Oster,M,?,...,Blue fish bite most probable,Keithe Cowley: Delmarva Now:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,16th May,2026.0,Unprovoked,Australia,Western Australia,Horseshoe Reef Rottnest Island,Skindiving,Steven Mattaboni,M,38,...,Great White Shark,ABC News: 9 News: 7 News: Simon De Marchi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,14th April,2026.0,UNprovoked,Maldives,Gaafu Alif Atoll,Kooddoo,Swimming,Not stated - on honeymoon,M,?,...,Unknown,The U.S. Sun: Simon De Marchi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3rd April,2026.0,Unprovoked,Australia,South Australia,Middleton Beach Fleurieu Peninsula Adelaide,Surfing,Oliver Tokic-Bensley,M,16,...,Bronze Whaler,ABC News: The Guardian: Andrew Currie and Bob...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
shark_df.columns

Index(['Date', 'Year', 'Type', 'Country', 'State', 'Location', 'Activity',
       'Name', 'Sex', 'Age', 'Injury', 'Fatal Y/N', 'Time', 'Species ',
       'Source', 'pdf', 'href formula', 'href', 'Case Number', 'Case Number.1',
       'original order', 'Unnamed: 21', 'Unnamed: 22'],
      dtype='object')

In [4]:
# Looking at all the values for each column with a function over the data frame.
for column in shark_df.columns:
    print(shark_df[column].value_counts())
    print()

Date
1957           9
1942           8
1958           7
1941           6
No date        6
              ..
12-Jun-2001    1
Jul-2001       1
03-Jul-2001    1
21-Jul-2001    1
1845-1853      1
Name: count, Length: 6129, dtype: int64

Year
2015.0    143
2017.0    141
2016.0    133
0.0       129
2011.0    128
         ...
1784.0      1
1834.0      1
1780.0      1
1779.0      1
1816.0      1
Name: count, Length: 261, dtype: int64

Type
Unprovoked             5239
Provoked                642
Invalid                 552
Watercraft              355
Sea Disaster            242
Questionable             27
Boat                      7
 Provoked                 2
UNprovoked                1
unprovoked                1
?                         1
Unconfirmed               1
Unverified                1
Under investigation       1
Name: count, dtype: int64

Country
USA                        2581
AUSTRALIA                  1482
SOUTH AFRICA                597
NEW ZEALAND                 144
PAPUA NEW GUINEA            136
                           ...
Sierra Leone                  1
BRITISH VIRGIN ISLANDS        1
NEVIS                         1
PALESTINIAN TERRITORIES       1
CEYLON (SRI LANKA)            1
Name: count, Length: 253, dtype: int64

State
Florida                       1192
New South Wales                522
Queensland                     355
Hawaii                         345
California                     328
                              ...
L'Etang-Sale                     1
Chatham Islands                  1
South Sinai, Gulf of Aqaba       1
Missouri                         1
Moala Island                     1
Name: count, Length: 948, dtype: int64

Location
New Smyrna Beach, Volusia County               191
Daytona Beach, Volusia County                   31
Ponce Inlet, Volusia County                     28
Myrtle Beach, Horry County                      22
Melbourne Beach, Brevard County                 20
                                              ...
Kibesillah, Mendocino County                     1
Big Bayou, St. Petersburg, Pinellas County       1
Park Rynie                                       1
Cocoa  Beach, Brevard County                     1
Below the English fort, Trincomalee              1
Name: count, Length: 4634, dtype: int64

Activity
Surfing                                          1152
Swimming                                         1016
Fishing                                           494
Spearfishing                                      392
Wading                                            178
                                                 ...
Floating on a small orange raft                     1
Filming & feeding captive sharks                    1
Attempting to drive shark away from the beach       1
Spearfishing / scuba diving                         1
Wreck of  large double sailing canoe                1
Name: count, Length: 1612, dtype: int64

Name
male                             679
female                           136
boy                               23
2 males                           17
boat                              14
                                ...
Gavin Duncan                       1
Kelly French                       1
Trenton Martin                     1
Mirjam Buser, a Swiss tourist      1
Jules Patterson                    1
Name: count, Length: 5804, dtype: int64

Sex
M        5685
F         811
M           5
?           2
F           2
N           2
 M          1
m           1
lli         1
M x 2       1
.           1
Name: count, dtype: int64

Age
16          92
19          90
17          89
18          85
17          85
            ..
46 & 34      1
12 or 13     1
18 or 20     1
86           1
13 or 14     1
Name: count, Length: 252, dtype: int64

Injury
FATAL                                                                   863
Foot bitten                                                             100
Survived                                                                 97
No injury                                                                85
Leg bitten                                                               81
                                                                       ...
Left knee & leg bitten                                                    1
Calf bitten & both hands injured                                          1
Back, buttocks, left hand & left side of face bitten                      1
No injury to occupants; boat damaged                                      1
FATAL. "Shark bit him in half, carrying away the lower extremities"       1
Name: count, Length: 4200, dtype: int64

Fatal Y/N
N          4944
Y          1493
UNKNOWN      71
 N            7
F             5
M             3
n             1
Nq            1
2017          1
Y x 2         1
N             1
y             1
Name: count, dtype: int64

Time
Afternoon               215
11h00                   140
Morning                 135
15h00                   127
16h00                   123
                       ...
Shortly before 12h00      1
13h19                     1
10h44                     1
1000                      1
19h00-20h00               1
Name: count, Length: 478, dtype: int64

Species
White shark                                                                                                                      194
Shark involvement prior to death was not confirmed                                                                               105
Invalid                                                                                                                          102
Shark involvement not confirmed                                                                                                   92
Tiger shark                                                                                                                       89
                                                                                                                                ...
14' to 16' white shark                                                                                                             1
Caribbean reef sharks                                                                                                              1
Tiger shark, less than 10'                                                                                                         1
18' white shark                                                                                                                    1
Said to involve a grey nurse shark that leapt out of the water and  seized the boy but species identification is questionable      1
Name: count, Length: 1748, dtype: int64

Source
K. McMurray, TrackingSharks.com                    131
C. Moore, GSAF                                     105
C. Creswell, GSAF                                  101
S. Petersohn, GSAF                                  82
B. Myatt, GSAF                                      59
                                                  ...
East London Daily Dispatch, 10/20/1998               1
Sun Sentinel. Fort Lauderdale, 10/25/1998, p.3B      1
O. Gadig & A. Xureb                                  1
Deseret News, 11/3/1998, p.A7                        1
S.W. Baker                                           1
Name: count, Length: 5415, dtype: int64

pdf
1907.10.16.R-HongKong.pdf            2
1921.11.27.a-b-Jack.pdf              2
1935.06.05.R-SolomonIslands.pdf      2
1916.12.08.a-b-German.pdf            2
1929.03.04.a-b.Roads-Aldridge.pdf    2
                                    ..
2003.04.19-SD.pdf                    1
2003.04.20.a-StephenFlowers.pdf      1
2003.04.20.b-Albright.pdf            1
2003.04.20.c-Ryan.pdf                1
ND-0001-Ceylon.pdf                   1
Name: count, Length: 6789, dtype: int64

href formula
http://sharkattackfile.net/spreadsheets/pdf_directory/1923.00.00.a-NJ fisherman.pdf          2
http://sharkattackfile.net/spreadsheets/pdf_directory/1934.12.23.a-b-Inman.pdf               2
http://sharkattackfile.net/spreadsheets/pdf_directory/1929.03.04.a-b.Roads-Aldridge.pdf      2
http://sharkattackfile.net/spreadsheets/pdf_directory/1916.07.12.a-b-Stillwell-Fisher.pdf    2
http://sharkattackfile.net/spreadsheets/pdf_directory/1931.09.21.a-b-Holaday-Barrows.pdf     2
                                                                                            ..
http://sharkattackfile.net/spreadsheets/pdf_directory/2003.04.18-PatrickAFB.pdf              1
http://sharkattackfile.net/spreadsheets/pdf_directory/2003.04.19-SD.pdf                      1
http://sharkattackfile.net/spreadsheets/pdf_directory/2003.04.20.a-StephenFlowers.pdf        1
http://sharkattackfile.net/spreadsheets/pdf_directory/2003.04.20.b-Albright.pdf              1
http://sharkattackfile.net/spreadsheets/pdf_directoryND-0001-Ceylon.pdf                      1
Name: count, Length: 6784, dtype: int64

href
http://sharkattackfile.net/spreadsheets/pdf_directory/w014.01.25-Grant.pdf           4
http://sharkattackfile.net/spreadsheets/pdf_directory/2014.10.02.b-Vandenberg.pdf    3
http://sharkattackfile.net/spreadsheets/pdf_directory/1934.12.23.a-b-Inman.pdf       2
http://sharkattackfile.net/spreadsheets/pdf_directory/1907.10.16.R-HongKong.pdf      2
http://sharkattackfile.net/spreadsheets/pdf_directory/1916.12.08.a-b-German.pdf      2
                                                                                    ..
http://sharkattackfile.net/spreadsheets/pdf_directory/2003.01.03-Menking.pdf         1
http://sharkattackfile.net/spreadsheets/pdf_directory/2003.01.17-scavenging.pdf      1
http://sharkattackfile.net/spreadsheets/pdf_directory/2003.02.08-Purcell.pdf         1
http://sharkattackfile.net/spreadsheets/pdf_directory/2003.02.11-Plumridge.pdf       1
http://sharkattackfile.net/spreadsheets/pdf_directoryND-0001-Ceylon.pdf              1
Name: count, Length: 6776, dtype: int64

Case Number
2021.07.23      2
1907.10.16.R    2
2012.09.02.b    2
2005.04.06      2
2009.12.18      2
               ..
2003.01.03      1
2003.01.17      1
2003.02.08      1
2003.02.11      1
ND.0001         1
Name: count, Length: 6777, dtype: int64

Case Number.1
2012.09.02.b    2
1913.08.27.R    2
1980.07.00      2
2021.12.06      2
1920.00.00.b    2
               ..
2002.12.21      1
2002.12.24      1
2002.12.29      1
2003.01.02      1
ND.0001         1
Name: count, Length: 6775, dtype: int64

original order
6369.0    2
569.0     2
6802.0    1
2272.0    1
2262.0    1
         ..
4536.0    1
4537.0    1
4538.0    1
4539.0    1
2.0       1
Name: count, Length: 6797, dtype: int64

Unnamed: 21
stopped here    1
Name: count, dtype: int64

Unnamed: 22
Teramo             1
change filename    1
Name: count, dtype: int64

In [5]:
shark_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7090 entries, 0 to 7089
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            7090 non-null   object
 1   Year            7088 non-null   float64
 2   Type            7072 non-null   object
 3   Country         7040 non-null   object
 4   State           6603 non-null   object
 5   Location        6523 non-null   object
 6   Activity        6507 non-null   object
 7   Name            6872 non-null   object
 8   Sex             6512 non-null   object
 9   Age             4096 non-null   object
 10  Injury          7054 non-null   object
 11  Fatal Y/N       6529 non-null   object
 12  Time            3563 non-null   object
 13  Species         3959 non-null   object
 14  Source          7070 non-null   object
 15  pdf             6799 non-null   object
 16  href formula    6794 non-null   object
 17  href            6796 non-null   object
 18  Case Number     6798 non-null   object
 19  Case Number.1   6797 non-null   object
 20  original order  6799 non-null   float64
 21  Unnamed: 21     1 non-null      object
 22  Unnamed: 22     2 non-null      object
dtypes: float64(2), object(21)
memory usage: 1.2+ MB

In [6]:
# Creating new dataframe to start cleaning up the data and store it seperately in case we want to go back.

shark_clean_df = shark_df.copy()
shark_clean_df.head()

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,24th May,2026.0,Unprovoked,Australia,Queensland,Kennedy Shoal,Spearfishing,Michael Jensz,M,39,...,Undetermined Bull shark most likely,Simon de Marchi: 9 News: 7 News: ABC News:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,17th May,2026.0,Questionable,USA,Maryland,Assateague State Park,Surfing,Brendan Oster,M,?,...,Blue fish bite most probable,Keithe Cowley: Delmarva Now:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,16th May,2026.0,Unprovoked,Australia,Western Australia,Horseshoe Reef Rottnest Island,Skindiving,Steven Mattaboni,M,38,...,Great White Shark,ABC News: 9 News: 7 News: Simon De Marchi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,14th April,2026.0,UNprovoked,Maldives,Gaafu Alif Atoll,Kooddoo,Swimming,Not stated - on honeymoon,M,?,...,Unknown,The U.S. Sun: Simon De Marchi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3rd April,2026.0,Unprovoked,Australia,South Australia,Middleton Beach Fleurieu Peninsula Adelaide,Surfing,Oliver Tokic-Bensley,M,16,...,Bronze Whaler,ABC News: The Guardian: Andrew Currie and Bob...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# Structuring the columns. lower() all the letters and add "_" instead of " "

shark_clean_df.columns = [column_name.lower() for column_name in shark_clean_df.columns]
shark_clean_df.columns

Index(['date', 'year', 'type', 'country', 'state', 'location', 'activity',
       'name', 'sex', 'age', 'injury', 'fatal y/n', 'time', 'species ',
       'source', 'pdf', 'href formula', 'href', 'case number', 'case number.1',
       'original order', 'unnamed: 21', 'unnamed: 22'],
      dtype='object')

In [8]:
# Structuring the columns. Using strip()

shark_clean_df.columns = shark_clean_df.columns.str.strip()
shark_clean_df.columns

Index(['date', 'year', 'type', 'country', 'state', 'location', 'activity',
       'name', 'sex', 'age', 'injury', 'fatal y/n', 'time', 'species',
       'source', 'pdf', 'href formula', 'href', 'case number', 'case number.1',
       'original order', 'unnamed: 21', 'unnamed: 22'],
      dtype='object')

In [9]:
# Cheking duplicates in the data

duplicated_df = shark_clean_df.duplicated().sum()
print("Number of duplicate rows:", duplicated_df)

Number of duplicate rows: 0

In [10]:
# Dropping the columns that we know for sure we will not use for analysis.

shark_clean_df = shark_clean_df.drop(columns=["pdf", "href formula", "href", "case number", "case number.1", "original order", "unnamed: 21", "unnamed: 22"])
shark_clean_df.head()

,date,year,type,country,state,location,activity,name,sex,age,injury,fatal y/n,time,species,source
0,24th May,2026.0,Unprovoked,Australia,Queensland,Kennedy Shoal,Spearfishing,Michael Jensz,M,39,Bite wounds to the head,Y,1100hrs,Undetermined Bull shark most likely,Simon de Marchi: 9 News: 7 News: ABC News:
1,17th May,2026.0,Questionable,USA,Maryland,Assateague State Park,Surfing,Brendan Oster,M,?,Bite wound to the hand,N,?,Blue fish bite most probable,Keithe Cowley: Delmarva Now:
2,16th May,2026.0,Unprovoked,Australia,Western Australia,Horseshoe Reef Rottnest Island,Skindiving,Steven Mattaboni,M,38,Severe injuries both legs,Y,1000hrs,Great White Shark,ABC News: 9 News: 7 News: Simon De Marchi
3,14th April,2026.0,UNprovoked,Maldives,Gaafu Alif Atoll,Kooddoo,Swimming,Not stated - on honeymoon,M,?,Leg strpped off flesh later amputated in hospital,N,?,Unknown,The U.S. Sun: Simon De Marchi
4,3rd April,2026.0,Unprovoked,Australia,South Australia,Middleton Beach Fleurieu Peninsula Adelaide,Surfing,Oliver Tokic-Bensley,M,16,Bite wound to R ankle,N,?,Bronze Whaler,ABC News: The Guardian: Andrew Currie and Bob...

In [11]:
shark_clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7090 entries, 0 to 7089
Data columns (total 15 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       7090 non-null   object
 1   year       7088 non-null   float64
 2   type       7072 non-null   object
 3   country    7040 non-null   object
 4   state      6603 non-null   object
 5   location   6523 non-null   object
 6   activity   6507 non-null   object
 7   name       6872 non-null   object
 8   sex        6512 non-null   object
 9   age        4096 non-null   object
 10  injury     7054 non-null   object
 11  fatal y/n  6529 non-null   object
 12  time       3563 non-null   object
 13  species    3959 non-null   object
 14  source     7070 non-null   object
dtypes: float64(1), object(14)
memory usage: 831.0+ KB

In [12]:
# Now we want to start filtering the data since we want to do only USA.
# In next few codes, we are trying to find if there are any other value than USA in country column that we should filter together with USA value
shark_clean_df["country"].unique()

array(['Australia', 'USA', 'Maldives', 'Bahamas', 'New Caledonia',
       'Cayman Islands', 'Brazil', 'US Virgin Islands', 'Mozambique',
       'French Polynesia', 'Samoa', 'Columbia', 'Costa Rica',
       'Puerto Rico', 'Spain', 'Canary Islands', 'South Africa',
       'Vanuatu', 'Jamaica', 'Israel', 'Mexico', 'Philippines',
       'Turks and Caicos', 'Egypt', 'Thailand', 'New Zealand', 'Hawaii',
       'Honduras', 'Indonesia', 'Morocco', 'Belize', 'Maldive Islands',
       'Tobago', 'AUSTRALIA', 'INDIA', 'TRINIDAD', 'BAHAMAS',
       'SOUTH AFRICA', 'MEXICO', 'NEW ZEALAND', 'EGYPT', 'BELIZE',
       'PHILIPPINES', 'Coral Sea', 'SPAIN', 'PORTUGAL', 'SAMOA',
       'COLOMBIA', 'ECUADOR', 'FRENCH POLYNESIA', 'NEW CALEDONIA',
       'TURKS and CaICOS', 'CUBA', 'BRAZIL', 'SEYCHELLES', 'ARGENTINA',
       'FIJI', 'MeXICO', 'ENGLAND', 'JAPAN', 'INDONESIA', 'JAMAICA',
       'MALDIVES', 'THAILAND', 'COLUMBIA', 'COSTA RICA',
       'British Overseas Territory', 'CANADA', 'JORDAN',
       'ST KITTS / NEVIS', 'ST MARTIN', 'PAPUA NEW GUINEA',
       'REUNION ISLAND', 'ISRAEL', 'CHINA', 'IRELAND', 'ITALY',
       'MALAYSIA', 'LIBYA', nan, 'MAURITIUS', 'SOLOMON ISLANDS',
       'ST HELENA, British overseas territory', 'COMOROS', 'REUNION',
       'UNITED KINGDOM', 'UNITED ARAB EMIRATES', 'CAPE VERDE', 'Fiji',
       'DOMINICAN REPUBLIC', 'CAYMAN ISLANDS', 'ARUBA', 'MOZAMBIQUE',
       'PUERTO RICO', 'ATLANTIC OCEAN', 'GREECE', 'ST. MARTIN', 'FRANCE',
       'TRINIDAD & TOBAGO', 'KIRIBATI', 'DIEGO GARCIA', 'TAIWAN',
       'PALESTINIAN TERRITORIES', 'GUAM', 'NIGERIA', 'TONGA', 'SCOTLAND',
       'CROATIA', 'SAUDI ARABIA', 'CHILE', 'ANTIGUA', 'KENYA', 'RUSSIA',
       'TURKS & CAICOS', 'UNITED ARAB EMIRATES (UAE)', 'AZORES',
       'SOUTH KOREA', 'MALTA', 'VIETNAM', 'MADAGASCAR', 'PANAMA',
       'SOMALIA', 'NEVIS', 'BRITISH VIRGIN ISLANDS', 'NORWAY', 'SENEGAL',
       'YEMEN', 'GULF OF ADEN', 'Sierra Leone', 'ST. MAARTIN',
       'GRAND CAYMAN', 'Seychelles', 'LIBERIA', 'VANUATU', 'MEXICO ',
       'HONDURAS', 'VENEZUELA', 'SRI LANKA', ' TONGA', 'URUGUAY',
       'MICRONESIA', 'CARIBBEAN SEA', 'OKINAWA', 'TANZANIA',
       'MARSHALL ISLANDS', 'EGYPT / ISRAEL', 'NORTHERN ARABIAN SEA',
       'HONG KONG', 'EL SALVADOR', 'ANGOLA', 'BERMUDA', 'MONTENEGRO',
       'IRAN', 'TUNISIA', 'NAMIBIA', 'NORTH ATLANTIC OCEAN',
       'SOUTH CHINA SEA', 'BANGLADESH', 'PALAU', 'WESTERN SAMOA',
       'PACIFIC OCEAN ', 'BRITISH ISLES', 'GRENADA', 'IRAQ', 'TURKEY',
       'SINGAPORE', 'NEW BRITAIN', 'SUDAN', 'JOHNSTON ISLAND',
       'SOUTH PACIFIC OCEAN', 'NEW GUINEA', 'RED SEA',
       'NORTH PACIFIC OCEAN', 'FEDERATED STATES OF MICRONESIA',
       'MID ATLANTIC OCEAN', 'ADMIRALTY ISLANDS', 'BRITISH WEST INDIES',
       'SOUTH ATLANTIC OCEAN', 'PERSIAN GULF', 'RED SEA / INDIAN OCEAN',
       'PACIFIC OCEAN', 'NORTH SEA', 'NICARAGUA ', 'MALDIVE ISLANDS',
       'AMERICAN SAMOA', 'ANDAMAN / NICOBAR ISLANDAS', 'GABON', 'MAYOTTE',
       'NORTH ATLANTIC OCEAN ', 'THE BALKANS', 'SUDAN?', 'MARTINIQUE',
       'INDIAN OCEAN', 'GUATEMALA', 'NETHERLANDS ANTILLES',
       'NORTHERN MARIANA ISLANDS', 'IRAN / IRAQ', 'JAVA', 'SIERRA LEONE',
       ' PHILIPPINES', 'NICARAGUA', 'CENTRAL PACIFIC',
       'SOLOMON ISLANDS / VANUATU', 'SOUTHWEST PACIFIC OCEAN',
       'BAY OF BENGAL', 'MID-PACIFC OCEAN', 'SLOVENIA', 'CURACAO',
       'ICELAND', 'ITALY / CROATIA', 'BARBADOS', 'MONACO', 'GUYANA',
       'HAITI', 'SAN DOMINGO', 'KUWAIT', 'YEMEN ', 'FALKLAND ISLANDS',
       'CRETE', 'CYPRUS', 'EGYPT ', 'WEST INDIES', 'BURMA', 'LEBANON',
       'PARAGUAY', 'BRITISH NEW GUINEA', 'CEYLON', 'OCEAN', 'GEORGIA',
       'SYRIA', 'TUVALU', 'INDIAN OCEAN?', 'GUINEA', 'ANDAMAN ISLANDS',
       'EQUATORIAL GUINEA / CAMEROON', 'COOK ISLANDS', 'TOBAGO', 'PERU',
       'AFRICA', 'ALGERIA', 'Coast of AFRICA', 'TASMAN SEA', 'GHANA',
       'GREENLAND', 'MEDITERRANEAN SEA', 'SWEDEN', 'ROATAN',
       'Between PORTUGAL & INDIA', 'DJIBOUTI', 'BAHREIN', 'KOREA',
       'RED SEA?', 'ASIA?', 'CEYLON (SRI LANKA)'], dtype=object)

In [13]:
shark_clean_df["country"].value_counts()

country
USA                        2581
AUSTRALIA                  1482
SOUTH AFRICA                597
NEW ZEALAND                 144
PAPUA NEW GUINEA            136
                           ...
Sierra Leone                  1
BRITISH VIRGIN ISLANDS        1
NEVIS                         1
PALESTINIAN TERRITORIES       1
CEYLON (SRI LANKA)            1
Name: count, Length: 253, dtype: int64

In [14]:
print(shark_clean_df["country"].sort_values().unique())

[' PHILIPPINES' ' TONGA' 'ADMIRALTY ISLANDS' 'AFRICA' 'ALGERIA'
 'AMERICAN SAMOA' 'ANDAMAN / NICOBAR ISLANDAS' 'ANDAMAN ISLANDS' 'ANGOLA'
 'ANTIGUA' 'ARGENTINA' 'ARUBA' 'ASIA?' 'ATLANTIC OCEAN' 'AUSTRALIA'
 'AZORES' 'Australia' 'BAHAMAS' 'BAHREIN' 'BANGLADESH' 'BARBADOS'
 'BAY OF BENGAL' 'BELIZE' 'BERMUDA' 'BRAZIL' 'BRITISH ISLES'
 'BRITISH NEW GUINEA' 'BRITISH VIRGIN ISLANDS' 'BRITISH WEST INDIES'
 'BURMA' 'Bahamas' 'Belize' 'Between PORTUGAL & INDIA' 'Brazil'
 'British Overseas Territory' 'CANADA' 'CAPE VERDE' 'CARIBBEAN SEA'
 'CAYMAN ISLANDS' 'CENTRAL PACIFIC' 'CEYLON' 'CEYLON (SRI LANKA)' 'CHILE'
 'CHINA' 'COLOMBIA' 'COLUMBIA' 'COMOROS' 'COOK ISLANDS' 'COSTA RICA'
 'CRETE' 'CROATIA' 'CUBA' 'CURACAO' 'CYPRUS' 'Canary Islands'
 'Cayman Islands' 'Coast of AFRICA' 'Columbia' 'Coral Sea' 'Costa Rica'
 'DIEGO GARCIA' 'DJIBOUTI' 'DOMINICAN REPUBLIC' 'ECUADOR' 'EGYPT' 'EGYPT '
 'EGYPT / ISRAEL' 'EL SALVADOR' 'ENGLAND' 'EQUATORIAL GUINEA / CAMEROON'
 'Egypt' 'FALKLAND ISLANDS' 'FEDERATED STATES OF MICRONESIA' 'FIJI'
 'FRANCE' 'FRENCH POLYNESIA' 'Fiji' 'French Polynesia' 'GABON' 'GEORGIA'
 'GHANA' 'GRAND CAYMAN' 'GREECE' 'GREENLAND' 'GRENADA' 'GUAM' 'GUATEMALA'
 'GUINEA' 'GULF OF ADEN' 'GUYANA' 'HAITI' 'HONDURAS' 'HONG KONG' 'Hawaii'
 'Honduras' 'ICELAND' 'INDIA' 'INDIAN OCEAN' 'INDIAN OCEAN?' 'INDONESIA'
 'IRAN' 'IRAN / IRAQ' 'IRAQ' 'IRELAND' 'ISRAEL' 'ITALY' 'ITALY / CROATIA'
 'Indonesia' 'Israel' 'JAMAICA' 'JAPAN' 'JAVA' 'JOHNSTON ISLAND' 'JORDAN'
 'Jamaica' 'KENYA' 'KIRIBATI' 'KOREA' 'KUWAIT' 'LEBANON' 'LIBERIA' 'LIBYA'
 'MADAGASCAR' 'MALAYSIA' 'MALDIVE ISLANDS' 'MALDIVES' 'MALTA'
 'MARSHALL ISLANDS' 'MARTINIQUE' 'MAURITIUS' 'MAYOTTE' 'MEDITERRANEAN SEA'
 'MEXICO' 'MEXICO ' 'MICRONESIA' 'MID ATLANTIC OCEAN' 'MID-PACIFC OCEAN'
 'MONACO' 'MONTENEGRO' 'MOZAMBIQUE' 'Maldive Islands' 'Maldives' 'MeXICO'
 'Mexico' 'Morocco' 'Mozambique' 'NAMIBIA' 'NETHERLANDS ANTILLES' 'NEVIS'
 'NEW BRITAIN' 'NEW CALEDONIA' 'NEW GUINEA' 'NEW ZEALAND' 'NICARAGUA'
 'NICARAGUA ' 'NIGERIA' 'NORTH ATLANTIC OCEAN' 'NORTH ATLANTIC OCEAN '
 'NORTH PACIFIC OCEAN' 'NORTH SEA' 'NORTHERN ARABIAN SEA'
 'NORTHERN MARIANA ISLANDS' 'NORWAY' 'New Caledonia' 'New Zealand' 'OCEAN'
 'OKINAWA' 'PACIFIC OCEAN' 'PACIFIC OCEAN ' 'PALAU'
 'PALESTINIAN TERRITORIES' 'PANAMA' 'PAPUA NEW GUINEA' 'PARAGUAY'
 'PERSIAN GULF' 'PERU' 'PHILIPPINES' 'PORTUGAL' 'PUERTO RICO'
 'Philippines' 'Puerto Rico' 'RED SEA' 'RED SEA / INDIAN OCEAN' 'RED SEA?'
 'REUNION' 'REUNION ISLAND' 'ROATAN' 'RUSSIA' 'SAMOA' 'SAN DOMINGO'
 'SAUDI ARABIA' 'SCOTLAND' 'SENEGAL' 'SEYCHELLES' 'SIERRA LEONE'
 'SINGAPORE' 'SLOVENIA' 'SOLOMON ISLANDS' 'SOLOMON ISLANDS / VANUATU'
 'SOMALIA' 'SOUTH AFRICA' 'SOUTH ATLANTIC OCEAN' 'SOUTH CHINA SEA'
 'SOUTH KOREA' 'SOUTH PACIFIC OCEAN' 'SOUTHWEST PACIFIC OCEAN' 'SPAIN'
 'SRI LANKA' 'ST HELENA, British overseas territory' 'ST KITTS / NEVIS'
 'ST MARTIN' 'ST. MAARTIN' 'ST. MARTIN' 'SUDAN' 'SUDAN?' 'SWEDEN' 'SYRIA'
 'Samoa' 'Seychelles' 'Sierra Leone' 'South Africa' 'Spain' 'TAIWAN'
 'TANZANIA' 'TASMAN SEA' 'THAILAND' 'THE BALKANS' 'TOBAGO' 'TONGA'
 'TRINIDAD' 'TRINIDAD & TOBAGO' 'TUNISIA' 'TURKEY' 'TURKS & CAICOS'
 'TURKS and CaICOS' 'TUVALU' 'Thailand' 'Tobago' 'Turks and Caicos'
 'UNITED ARAB EMIRATES' 'UNITED ARAB EMIRATES (UAE)' 'UNITED KINGDOM'
 'URUGUAY' 'US Virgin Islands' 'USA' 'VANUATU' 'VENEZUELA' 'VIETNAM'
 'Vanuatu' 'WEST INDIES' 'WESTERN SAMOA' 'YEMEN' 'YEMEN ' nan]

In [15]:
# We found out that Hawaii was one of the values in country field. So, we mapped it together with USA value
shark_clean_df["country"] = shark_clean_df["country"].replace({
    "Hawaii": "USA"
})
shark_clean_df["country"].value_counts()

country
USA                       2582
AUSTRALIA                 1482
SOUTH AFRICA               597
NEW ZEALAND                144
PAPUA NEW GUINEA           136
                          ...
ST. MAARTIN                  1
GULF OF ADEN                 1
BRITISH VIRGIN ISLANDS       1
NEVIS                        1
CEYLON (SRI LANKA)           1
Name: count, Length: 252, dtype: int64

In [16]:
# In this section, we focus exclusively on shark attacks within the USA to specialize our analysis on this region

shark_clean_df_usa = shark_clean_df[shark_clean_df["country"].isin(["USA"])]
shark_clean_df_usa.head()

,date,year,type,country,state,location,activity,name,sex,age,injury,fatal y/n,time,species,source
1,17th May,2026.0,Questionable,USA,Maryland,Assateague State Park,Surfing,Brendan Oster,M,?,Bite wound to the hand,N,?,Blue fish bite most probable,Keithe Cowley: Delmarva Now:
8,18th March,2026.0,Unprovoked,USA,California,Big River Beach Mendocino County,Surfing,Unknown,M,39,Injuries to both legs and feet,N,1715hrs,Great White Shark,US Sun: Mendocino Coast News:Melissa Michaelson:
21,13th January,2026.0,Unprovoked,USA,California,Mendocino County,Surfing,Tommy Civic,M,26,Minor puncture wounds to upper left thigh,N,0830hrs,Suspected GWS,Bob Myatt GSAF
28,21st December,2025.0,Unprovoked,USA,California,Lovers Point Pacific Grove,Swimming,Erica Fox,F,55,Taken by shark body recovered with multiple in...,Y,1200hrs,Great White Shark,Kevin McMurray Tracking sharks.com: Ralph Coll...
29,12th December,2025.0,Unprovoked,USA,Sonoma County California,Salmon Creek,Surfing,Unknown,M,?,Hand Injury,N,0800hrs,Suspected Great White Shark,Kevin McMurray Tracking sharks.com:Andrew Curr...

In [17]:
# Now, we will quantify the frequency of shark attacks per state within the USA. 
# This will help us highlight which regions present the highest number of reported cases

shark_clean_df_usa.state.value_counts().reset_index()

                           state  count
0                        Florida   1192
1                         Hawaii    345
2                     California    328
3                 South Carolina    174
4                 North Carolina    119
5                          Texas     83
6                     New Jersey     56
7                       New York     45
8                         Oregon     31
9                       Virginia     19
10                 Massachusetts     19
11                     Louisiana     18
12                       Georgia     17
13                   Puerto Rico     17
14                       Alabama     17
15                      Maryland     11
16                      Delaware      8
17                  Rhode Island      8
18                   Mississippi      8
19                   Connecticut      6
20             US Virgin Islands      5
21                     New York       3
22                          Maui      3
23                 Palmyra Atoll      2
24                    Washington      2
25               North Carolina       2
26                         Maine      2
27                    East coast      2
28                          Guam      2
29                  Pennsylvania      1
30                      Missouri      1
31                        Alaska      1
32                    New Jersey      1
33                  Midway Atoll      1
34               South Carolina       1
35        North & South Carolina      1
36                North Carolina      1
37                Carolina coast      1
38                      Florida       1
39                   Wake Island      1
40                      Illinois      1
41                Johnston Atoll      1
42                       Bahamas      1
43                    New Mexico      1
44                          Utah      1
45      Sonoma County California      1
46  Hawaii West Coast Big Island      1
47                Off California      1
48                Long Island NY      1
49                        Floria      1
50                     Galveston      1
51                         Samoa      1
52                      Kentucky      1
53               Noirth Carolina      1
54                   Los Angeles      1
55                       BAHAMAS      1
56      Franklin County, Florida      1
57                Virgin Islands      1
58                Cayman Islands      1
59                          CUBA      1

In [18]:
# Standardizing State Names
shark_clean_df_usa = shark_clean_df_usa.replace ({"floria":"florida", "franklin county, florida" : "florida" , "east coast":"florida" , "long island ny":"new york",
                          "north carolina":"north & south carolina",
                          "carolina coast":"north & south carolina" , "noirth carolina":"north & south carolina",
                          "north carolina":"north & south carolina" , "south carolina":"north & south carolina" ,
                          "sonoma county california":"california","off california":"california" , "los angeles":"california",
                          "hawaii west coast big island":"hawai", "maui":"hawai" , "hawaii west coast big island":"hawai" ,
                            "galveston":"texas"})
shark_clean_df_usa.head()

,date,year,type,country,state,location,activity,name,sex,age,injury,fatal y/n,time,species,source
1,17th May,2026.0,Questionable,USA,Maryland,Assateague State Park,Surfing,Brendan Oster,M,?,Bite wound to the hand,N,?,Blue fish bite most probable,Keithe Cowley: Delmarva Now:
8,18th March,2026.0,Unprovoked,USA,California,Big River Beach Mendocino County,Surfing,Unknown,M,39,Injuries to both legs and feet,N,1715hrs,Great White Shark,US Sun: Mendocino Coast News:Melissa Michaelson:
21,13th January,2026.0,Unprovoked,USA,California,Mendocino County,Surfing,Tommy Civic,M,26,Minor puncture wounds to upper left thigh,N,0830hrs,Suspected GWS,Bob Myatt GSAF
28,21st December,2025.0,Unprovoked,USA,California,Lovers Point Pacific Grove,Swimming,Erica Fox,F,55,Taken by shark body recovered with multiple in...,Y,1200hrs,Great White Shark,Kevin McMurray Tracking sharks.com: Ralph Coll...
29,12th December,2025.0,Unprovoked,USA,Sonoma County California,Salmon Creek,Surfing,Unknown,M,?,Hand Injury,N,0800hrs,Suspected Great White Shark,Kevin McMurray Tracking sharks.com:Andrew Curr...

In [19]:
# Excluding non-mainland US territories from the analysis.
# These territories (e.g. Puerto Rico, Guam, US Virgin Islands) are not representative of mainland USA.
# We use .str.lower() to ensure the comparison is accurate, since the state column has mixed strings.

territory_to_exclude = ['puerto rico', 'bahamas', 'virgin islands', 'wake island', 'midway atoll', 
                         'cuba', 'palmyra atoll', 'johnston atoll', 'cayman islands', 'samoa', 
                         'guam', 'us virgin islands']

shark_clean_usa_filtered_df = shark_clean_df_usa[~shark_clean_df_usa['state'].str.lower().isin(territory_to_exclude)]
shark_clean_usa_filtered_df.state.value_counts().reset_index()

                           state  count
0                        Florida   1192
1                         Hawaii    345
2                     California    328
3                 South Carolina    174
4                 North Carolina    119
5                          Texas     83
6                     New Jersey     56
7                       New York     45
8                         Oregon     31
9                       Virginia     19
10                 Massachusetts     19
11                     Louisiana     18
12                       Alabama     17
13                       Georgia     17
14                      Maryland     11
15                   Mississippi      8
16                  Rhode Island      8
17                      Delaware      8
18                   Connecticut      6
19                     New York       3
20                          Maui      3
21                    East coast      2
22                         Maine      2
23                    Washington      2
24               North Carolina       2
25               Noirth Carolina      1
26                      Missouri      1
27                    New Jersey      1
28                North Carolina      1
29                      Illinois      1
30                  Pennsylvania      1
31      Sonoma County California      1
32                      Florida       1
33                Carolina coast      1
34        North & South Carolina      1
35               South Carolina       1
36                        Alaska      1
37                          Utah      1
38                    New Mexico      1
39                      Kentucky      1
40  Hawaii West Coast Big Island      1
41                Off California      1
42                Long Island NY      1
43      Franklin County, Florida      1
44                        Floria      1
45                     Galveston      1
46                   Los Angeles      1

In [20]:
# Checking the nulls for state column
shark_clean_usa_filtered_df['state'].isnull().sum()

np.int64(7)

In [21]:
# Checking the actual rows with null values in state column to understand what needs to be done with those rows.

shark_clean_usa_filtered_df[shark_clean_usa_filtered_df['state'].isnull()]

,date,year,type,country,state,location,activity,name,sex,age,injury,fatal y/n,time,species,source
936,00.Feb.2017,2017.0,Unprovoked,USA,NaN,Southern USA,Not stated,male non-hipanic,m,13,Shoulder injuries,N,Not stated,Unknown,John Sheele MD
3169,09-Dec-1994,1994.0,Sea Disaster,USA,NaN,1200 miles east of New Jersey,NaN,The Salvador Allende sank in heavy seas with t...,M,NaN,Sharks took some of the crew,Y,NaN,NaN,"New York Times, 12/11/1994 and Rotomedia.com"
3350,17-Jul-1991,1991.0,Questionable,USA,NaN,NaN,Fishing,male,M,70,Injury to right shin.,N,NaN,Shark involvement unconfirmed,GSAF Medical Library
4267,14-Dec-1967,1967.0,Provoked,USA,NaN,NaN,NaN,Joe Stinson,M,NaN,"Head, shoulder, arm lacerated. Recorded as PRO...",N,NaN,NaN,H.D.Baldridge (1994) SAF Case #1566
6290,1904,1904.0,Invalid,USA,NaN,NaN,Diving on a wreck,Egan,M,NaN,Leg bitten,NaN,NaN,Questionable,"New York Times, 6/21/1914"
6904,Aug-24-1806,1896.0,Sea Disaster,USA,NaN,NaN,NaN,Crew of the schooner Mary,M,NaN,Shark scavenged on the dead sailors,NaN,NaN,NaN,"Evening Post, 9/6/1806"
6926,Reported 12-Jul-1771,1771.0,Unprovoked,USA,NaN,Damiscotte,Fishing,male,M,NaN,FATAL,Y,NaN,NaN,"C. Moore, GSAF"

In [22]:
# Decided to drop the rows with null data for column state since its only 7 rows

shark_clean_usa_filtered_df = shark_clean_usa_filtered_df.dropna(subset=["state"])
shark_clean_usa_filtered_df.isnull().sum()

date            0
year            0
type            8
country         0
state           0
location       45
activity      146
name           33
sex           103
age           785
injury          6
fatal y/n     187
time          886
species      1038
source          7
dtype: int64

In [23]:
# Now, we will calculate the number of shark attacks per state in the USA to identify the regions with the highest frequency

shark_clean_usa_filtered_df['state'].value_counts()

state
Florida                         1192
Hawaii                           345
California                       328
South Carolina                   174
North Carolina                   119
Texas                             83
New Jersey                        56
New York                          45
Oregon                            31
Virginia                          19
Massachusetts                     19
Louisiana                         18
Alabama                           17
Georgia                           17
Maryland                          11
Mississippi                        8
Rhode Island                       8
Delaware                           8
Connecticut                        6
New York                           3
Maui                               3
East coast                         2
Maine                              2
Washington                         2
North Carolina                     2
Noirth Carolina                    1
Missouri                           1
 New Jersey                        1
 North Carolina                    1
Illinois                           1
Pennsylvania                       1
Sonoma County California           1
Florida                            1
Carolina coast                     1
North & South Carolina             1
South Carolina                     1
Alaska                             1
 Utah                              1
New Mexico                         1
Kentucky                           1
Hawaii West Coast Big Island       1
Off California                     1
Long Island NY                     1
Franklin County, Florida           1
Floria                             1
Galveston                          1
Los Angeles                        1
Name: count, dtype: int64

In [24]:
# Calculating Percentage of Attacks by State 
shark_clean_usa_filtered_df['state'].value_counts(normalize=True) * 100

state
Florida                         46.929134
Hawaii                          13.582677
California                      12.913386
South Carolina                   6.850394
North Carolina                   4.685039
Texas                            3.267717
New Jersey                       2.204724
New York                         1.771654
Oregon                           1.220472
Virginia                         0.748031
Massachusetts                    0.748031
Louisiana                        0.708661
Alabama                          0.669291
Georgia                          0.669291
Maryland                         0.433071
Mississippi                      0.314961
Rhode Island                     0.314961
Delaware                         0.314961
Connecticut                      0.236220
New York                         0.118110
Maui                             0.118110
East coast                       0.078740
Maine                            0.078740
Washington                       0.078740
North Carolina                   0.078740
Noirth Carolina                  0.039370
Missouri                         0.039370
 New Jersey                      0.039370
 North Carolina                  0.039370
Illinois                         0.039370
Pennsylvania                     0.039370
Sonoma County California         0.039370
Florida                          0.039370
Carolina coast                   0.039370
North & South Carolina           0.039370
South Carolina                   0.039370
Alaska                           0.039370
 Utah                            0.039370
New Mexico                       0.039370
Kentucky                         0.039370
Hawaii West Coast Big Island     0.039370
Off California                   0.039370
Long Island NY                   0.039370
Franklin County, Florida         0.039370
Floria                           0.039370
Galveston                        0.039370
Los Angeles                      0.039370
Name: proportion, dtype: float64

In [25]:
# Find out how many nulls in Fatal column
shark_clean_usa_filtered_df["fatal y/n"].isnull().sum()

np.int64(187)

In [26]:
# How many unique entries are there in Fatal
shark_clean_usa_filtered_df["fatal y/n"].unique()

array(['N', 'Y', 'F', 'n', 'Nq', nan, 'UNKNOWN', 'Y x 2'], dtype=object)

In [27]:
# Let's clean the fatal column

# Step 1: Check how many unique items there are in this column
shark_clean_usa_filtered_df["fatal y/n"].unique()

# Step 2: Count how many values in the column. Include dropna=False so it shows missing values too.
shark_clean_usa_filtered_df["fatal y/n"].value_counts(dropna=False)

# Step 3: Replace UNKNOWN with NaN
shark_clean_usa_filtered_df["fatal y/n"] = shark_clean_usa_filtered_df["fatal y/n"].replace("UNKNOWN", np.nan)

# Step 4: Make all values a string (to deal with integers), remove white space and make them all uppercase (to deal with y & n) 
shark_clean_usa_filtered_df["fatal y/n"] = (
    shark_clean_usa_filtered_df["fatal y/n"]
    .astype("string")
    .str.strip()
    .str.lower()
)

# Step 5: Made a decision to only keep Y or N and add everything else to NaN, using a loop
valid_values = ["y", "n"]

# NB: .items() returns 2 values (is a tuple), the index and the Y/N (row, column) so you need to include BOTH in the for loop
for index, value in shark_clean_usa_filtered_df["fatal y/n"].items():

    # Added pd.notna(value) because when I converted to a string, pandas created NA values and was giving a "boolean value of NA is ambiguous" error
    if pd.notna(value) and value not in valid_values:

        # Using .loc to select a row & column. So for each row set the column value to NaN
        shark_clean_usa_filtered_df.loc[index,"fatal y/n"] = np.nan
        

shark_clean_usa_filtered_df["fatal y/n"].value_counts(dropna=False)

fatal y/n
n       2143
<NA>     208
y        189
Name: count, dtype: Int64

In [28]:
# Looking at the type column and start cleaning.

shark_clean_usa_filtered_df["type"].value_counts()

type
Unprovoked             1986
Provoked                232
Invalid                 192
Watercraft               80
Sea Disaster             32
Questionable              7
Unconfirmed               1
Under investigation       1
Boat                      1
Name: count, dtype: int64

In [29]:
# Replacing and mapping the column names again for type column to clean up the column.

shark_clean_usa_filtered_df["type"] = shark_clean_usa_filtered_df["type"].replace({
    " Provoked": "Provoked",
    "UNprovoked": "Unprovoked",
    "unprovoked": "Unprovoked",
    "?": "Invalid",
    "Boat": "Watercraft",
    "Unconfirmed": "Invalid",
    "Unverified": "Invalid",
    "Under investigation": "Invalid"
})

In [30]:
shark_clean_usa_filtered_df["type"].value_counts()

type
Unprovoked      1986
Provoked         232
Invalid          194
Watercraft        81
Sea Disaster      32
Questionable       7
Name: count, dtype: int64

In [31]:
# Checking the nulls in type column
shark_clean_usa_filtered_df["type"].isnull().sum()

np.int64(8)

In [32]:
shark_clean_usa_filtered_df[shark_clean_usa_filtered_df["type"].isnull()]

,date,year,type,country,state,location,activity,name,sex,age,injury,fatal y/n,time,species,source
393,21-Jul-2021,2021.0,NaN,USA,Florida,"Near Patrick AFB, Brevard County",NaN,Katie Wood,F,35,"Small laceration to ankle, shark involvement n...",n,12h23,NaN,"J Marchand, GSAF"
482,21-Oct-2020,2020.0,NaN,USA,North Carolina,"Emerald Isle, Carteret County",Surfing,Erik Martynuik,M,NaN,Laceration to knee and foot,n,Sunset,Shark involvement not confirmed,"C. Creswell, GSAF"
487,21-Sep-2020,2020.0,NaN,USA,Hawaii,"Charley Young Beach, Maui",Swimming,female,F,61,Lacerations and puncture wounds to shoulder,n,11h00,Injuries not caused by a shark,Maui Now. 9/21/2020
491,16-Sep-2020,2020.0,NaN,USA,Florida,"Daytona Beach Shores, Volusia County",Swimming,Eric Bowman,M,48,Minor cuts and punctures to left foot,n,15h20,Shark involvement not confirmed,"K. McMurray, TrackingSharks.com"
494,08-Sep-2020,2020.0,NaN,USA,Florida,Canaveral National Seashore,Surf fishing,male,M,54,Hand bitten that was holding a fish PROVOKED I...,n,NaN,4' to 5' shark,"Click Orlando, 9/8/2020"
504,19-Aug-2020,2020.0,NaN,USA,South Carolina,"Myrtle Beach, Horry County",Wading,Nicole Stowerss,F,NaN,Minor injury to arm by a fish,n,1415,NaN,"C. Creswell, GSF"
533,04-Jun-2020,2020.0,NaN,USA,Delaware,"Herring Point, Sussex County",Skimboarding,Holt Baker,M,12,Puncture wounds to leg,n,13h00,Shark involvement unconfirmed but considered p...,"K. McMurray, TrackingSharks.com"
543,29-Apr-2020,2020.0,NaN,USA,California,"Moonlight Beach, San Diego County",Body Boarding,male,M,16,Minor injury to ankle from stingray,n,17h45,NaN,"K. McMurray, TrackingSharks.com and M. Michael..."

In [33]:
# Droping null rows in type column because there are only 18 null values. So, the missing part will be less than 1%

shark_clean_usa_filtered_df = shark_clean_usa_filtered_df.dropna(subset=["type"])
shark_clean_usa_filtered_df.isnull().sum()

date            0
year            0
type            0
country         0
state           0
location       45
activity      145
name           33
sex           103
age           783
injury          6
fatal y/n     208
time          885
species      1035
source          7
dtype: int64

In [34]:
# Defining values in Type column. Investigating the potential impact over the Provoked or Unprovoked analysis.
# Investigating Invalid rows to confirm no shark involvement

invalid_df = shark_clean_usa_filtered_df[shark_clean_usa_filtered_df["type"] == "Invalid"]
print(invalid_df[["type", "injury", "species"]].to_string())

         type                                                                                                                                                                                                                           injury                                                                                                                                                                                  species
623   Invalid                                                                                                                                                                                                            Unknown / Unconfirmed                                                                                                                                                                                      NaN
737   Invalid                                                                                                                                                                    Single laceration to right thigh inconsistent with shark bite                                                                                                                                                                                      NaN
740   Invalid                                                                                                                                                                          Laceration to left thigh, possibly caused by surfboard                                                                                                                                                                                       NaN
745   Invalid                                                                                                                                                                                                         Injury to knee/lower leg                                                                                                                                      Injury most likely caused by barracuda, not a shark
750   Invalid                                                                                                                                                                                     Injury to left lower leg from surfboard skeg                                                                                                                                                                                      NaN
832   Invalid                                                                                                                                                                                           Lacerations to right ankle, foot & toe                                                                                                                                                                             Questionable
860   Invalid                                                                                                                                                                                               Abrasions and cuts to sole of foot                                                                                                                                                                            A small shark
868   Invalid                                                                                                                                                                                                                     Foot injured                                                                                                                                                          Shark involvement not confirmed
878   Invalid                                                                                                                                                                                              Arm injured by hook, not by a shark                                                                                                                                                                    No shark invovlement
898   Invalid                                                                                                                                                                              Laceration to thigh, likely caused by surfboard fin                                                                                                                                                        Shark involvement highly doubtful
904   Invalid                                                                                                                                                                                                 Alleged laceration to left ankle                                                                                                                                           No shark invovlement - it ws a publicity stunt
906   Invalid                                                                                                                                                                                        Laceration & puncture wounds to left foot                                                                                                                                                          Shark involvement not confirmed
951   Invalid                                                                                                                                                                                                       Cuts to right ankle & foot                                                                                                                                                          Shark involvement not confirmed
1023  Invalid                                                                                                                                                                                                         No injury, board damaged                                                                                                                      Said to involve an 8' shark but more likely damage caused by debris
1050  Invalid                                                                                                                                          Fell off board when spinner shark leapt from the water next to him. No injury to surfer                                                                                                                                                                                      NaN
1056  Invalid                                                                                                                                                                                      Board reportedly bumped by shark. No injury                                                                                                                                                          Shark involvement not confirmed
1093  Invalid                                                                                                                                                                                                           Lower left leg injured                                                                                                                                                          Shark involvement not confirmed
1103  Invalid                                                                                                                                                                                                          Left foot bitten by eel                                                                                                                                                                     No shark involvement
1132  Invalid                                                                                                                                                                                                         Wound to right lower leg                                                                                                                                                          Shark involvement not confirmed
1143  Invalid                                                                                                                                                                              2' cut to dorsum of foot, 2 puncture wounds to sole                                                                                                                 Thought to involve a 3' to 4' shark, but shark involvement not confirmed
1150  Invalid                                                                                                                                                                                                               Laceration to back                                                                                                                                                           Shark involvement not cofirmed
1161  Invalid                                                                                                                                                                                                         Minor lacerations to leg                                                                                                                                                          Shark involvement not confirmed
1218  Invalid                                                                                                                                            During his 16-hour swim to shore, he was circled by a shark but it did not injure him                                                                                                                                                                     No shark involvement
1257  Invalid                                                                                                                                                                                                     A hoax, no shark involvement                                                                                                                                                                     No shark involvement
1265  Invalid                                                                                                                                                                                                  Shark involvement not confirmed                                                                                                                                                          Shark involvement not confirmed
1316  Invalid                                                                                                                          No injury. No attack. 12' white shark appeared curious, not aggressive & departed when prodded by spear                                                                                                                                                                     No shark involvement
1391  Invalid                                                                                                             Puncture wound to torso. Reported as a bite by a leopard shark, the tooth fragment appears to be that of a bony fish                                                                                                                                                                     No shark involvement
1434  Invalid                                                                                                                                                                                                     Shark bites were post-mortem                                                                                                                                                                                  Invalid
1490  Invalid                                                                                                                                                                                                                Laceration to toe                                                                                                                                                          Shark involvement not confirmed
1519  Invalid                                                                                                                                                                                                    Shark involvement unconfirmed                                                                                                                                                          Shark involvement not confirmed
1536  Invalid                                                                                                                                                                           Laceration to foot. Injured by a stingray, not a shark                                                                                                                                                                     No shark involvement
1640  Invalid                                                                                                                                                                                                           Abrasions to left hand                                                                                                                                                          Shark involvement not confirmed
1645  Invalid                                                                                                                                                                                                          Puncture wounds to foot                                                                                                                                                          Shark involvement not confirmed
1761  Invalid                                                                                                                                                 Minor abrasions to legs when she was lifted on the back of a large marine animal                                                                                                                                                          Shark involvement not confirmed
1827  Invalid                                                                                                                                                                                                    Puncture wounds to right foot                                                                                                                                                          Shark involvement not confirmed
1849  Invalid                                                                                                                                                                                                                            FATAL                                                                                                                                           Shark involvement prior to death not confirmed
1875  Invalid                                                                                                                                                                                                          Puncture wounds to foot                                                                                                                                                          Shark involvement not confirmed
1876  Invalid                                                                                                                                                                                              2-inch laceration to upper left arm                                                                                                                                            Shark involvement probable, but not confirmed
1894  Invalid                                                                                                                                                                                                                          Missing                                                                                                                                                          Shark involvement not confirmed
1970  Invalid                                                                                                                                                                                               Death was probably due to drowning                                                                                                                                                          Shark involvement not confirmed
1975  Invalid                                                                                                                                                                                                                      Calf bitten                                                                                                                                                          Shark involvement not confirmed
1977  Invalid                                                                                                                                                                                                                   Minor injuries                                                                                                                                                          Shark involvement not confirmed
1993  Invalid                                                                                                               Bruises, abrasions and some spinal and nerve damage when collided with marine animal, possibly a shark or dolphin.                                                                                                                                                          Shark involvement not confirmed
1998  Invalid                                                                                                                                                                                         Probable drowning with post-mortem bites                                                                                                                                           Shark involvement prior to death not confirmed
2084  Invalid                                                                                                                                                                                     Shark involvement prior to death unconfirmed                                                                                                                                       Shark involvement prior to death was not confirmed
2119  Invalid                                                                                                                                                                                       Foot injured. Shark involvment uncomfirmed                                                                                                                                                          Shark involvement not confirmed

In [35]:
# Count before
print("Total rows before dropping Invalid:", len(shark_clean_usa_filtered_df))
print("Invalid rows to be dropped:", len(invalid_df))

Total rows before dropping Invalid: 2532
Invalid rows to be dropped: 194

In [36]:
# Droping Invalid rows and save to dataframe
shark_clean_usa_filtered_df = shark_clean_usa_filtered_df[shark_clean_usa_filtered_df["type"] != "Invalid"]

In [37]:
# Count after dropping
print("Total rows after dropping Invalid:", len(shark_clean_usa_filtered_df))

# Confirming Invalid no longer exists in the type column
print(shark_clean_usa_filtered_df["type"].value_counts())

Total rows after dropping Invalid: 2338
type
Unprovoked      1986
Provoked         232
Watercraft        81
Sea Disaster      32
Questionable       7
Name: count, dtype: int64

In [38]:
# Dropping Questionable rows
# Upon inspection of Injury and Species columns, these records either confirmed no shark involvement, were caused by other animals, or lacked sufficient information to classify.
# Keeping them would make our Provoked vs Unprovoked analysis cleaner.
shark_clean_usa_filtered_df = shark_clean_usa_filtered_df[shark_clean_usa_filtered_df["type"] != "Questionable"]

In [39]:
# Investigating Sea Dissasaster rows
# Step 1 - Checking Sea Disaster rows to inspect species data later
# We want to check if Sea Disaster rows have enough species data to be useful in our analysis
sea_disaster_df = shark_clean_usa_filtered_df[shark_clean_usa_filtered_df["type"] == "Sea Disaster"]

# Step 2 - Counting total Sea Disaster rows
print("Total Sea Disaster rows:", len(sea_disaster_df))

# Step 3 - Counting rows with no species data
print("Rows with no species data:", sea_disaster_df["species"].isna().sum())

# Step 4 - Counting rows with species data
print("Rows with species data:", sea_disaster_df["species"].notna().sum())

Total Sea Disaster rows: 32
Rows with no species data: 30
Rows with species data: 2

In [40]:
# Dropping Sea Disaster rows
# Reason: Almost no species data available, and context is completely different from regular shark interactions - sharks were scavenging accident victims, not actively attacking humans. 
# Dropping keeps our analysis focused and clean.
shark_clean_usa_filtered_df = shark_clean_usa_filtered_df[shark_clean_usa_filtered_df["type"] != "Sea Disaster"]

# Displaying after dropped the rows
print("Rows after dropping Sea Disaster:", len(shark_clean_usa_filtered_df))

Rows after dropping Sea Disaster: 2299

In [41]:
# Confirming Sea Disaster no longer exists in the type column
shark_clean_usa_filtered_df["type"].value_counts()

type
Unprovoked    1986
Provoked       232
Watercraft      81
Name: count, dtype: int64

In [42]:
# Looking at the values in the column Species
shark_clean_usa_filtered_df['species'].value_counts()

species
White shark                  56
4' shark                     41
Tiger shark                  30
4' to 5' shark               24
3' shark                     23
                             ..
Possibly a 10' bull shark     1
Possibly a 6' bull shark      1
White shark, 12'              1
Nurse shark, 2' to 3'         1
White shark, 1,900-lb         1
Name: count, Length: 681, dtype: int64

In [43]:
# Step 1 - Cleaning by using strip() (whitespace) in Species column
# This prevents mismatches caused by invisible spaces
shark_clean_usa_filtered_df['species'] = shark_clean_usa_filtered_df['species'].str.strip()

In [44]:
# Step 2 - Convert all Species values to lowercase to standardizes the text.
shark_clean_usa_filtered_df['species'] = shark_clean_usa_filtered_df['species'].str.lower()

In [45]:
# Step 3 - Fill missing species values with 'unknown'
# We keep these rows in the dataset since the incident data is still valid
# They will be grouped into 'Other / Unknown' in later stage
shark_clean_usa_filtered_df['species'] = shark_clean_usa_filtered_df['species'].fillna('unknown')

In [46]:
# Step 4 - Classify species into 4 groups: White Shark, Tiger Shark, Bull Shark, Other/Unknown
# These 3 species are the most commonly cited in shark incident reports.
# All other species and unknowns are grouped into 'Other / Unknown' to simplify the analysis.
# We use str.contains() to catch variations like 'white shark, 12ft' or 'suspected white shark'
shark_clean_usa_filtered_df.loc[shark_clean_usa_filtered_df['species'].str.contains('white'), 'species'] = 'White Shark'
shark_clean_usa_filtered_df.loc[shark_clean_usa_filtered_df['species'].str.contains('tiger'), 'species'] = 'Tiger Shark'
shark_clean_usa_filtered_df.loc[shark_clean_usa_filtered_df['species'].str.contains('bull'), 'species'] = 'Bull Shark'

In [47]:
# Step 5 - Group everything that is not White, Tiger or Bull into 'Other / Unknown'
not_white = shark_clean_usa_filtered_df['species'] != 'White Shark'
not_tiger = shark_clean_usa_filtered_df['species'] != 'Tiger Shark'
not_bull = shark_clean_usa_filtered_df['species'] != 'Bull Shark'

condition_species = not_white & not_tiger & not_bull
shark_clean_usa_filtered_df.loc[condition_species, 'species'] = 'Other / Unknown'

In [48]:
shark_clean_usa_filtered_df['species'].value_counts()

species
Other / Unknown    1833
White Shark         231
Tiger Shark         147
Bull Shark           88
Name: count, dtype: int64

In [49]:
# Fatality Rate - the most powerful information for our narrative
# This shows what percentage of all shark incidents in the USA resulted in a fatality

total_incidents = len(shark_clean_usa_filtered_df)
fatal_incidents = (shark_clean_usa_filtered_df["fatal y/n"] == "y").sum()
fatality_rate = (fatal_incidents / total_incidents * 100).round(2)

print(f"Total shark incidents in USA: {total_incidents}")
print(f"Fatal incidents: {fatal_incidents}")
print(f"Fatality rate: {fatality_rate}%")
print(f"Not fatal rate: {round(100 - fatality_rate, 2)}%")

Total shark incidents in USA: 2299
Fatal incidents: 169
Fatality rate: 7.35%
Not fatal rate: 92.65%

In [50]:
# We are using 'values = year' to tell pandas which rows to count since they all have a year entry
pivot = pd.pivot_table(
    shark_clean_usa_filtered_df,
    index='type',
    columns='fatal y/n',
    values='year',
    aggfunc='count',
    fill_value=0
)

pivot['Total'] = pivot.sum(axis=1)

# Divide the fatal = y entries by the total amount (rounded to 2 decimal places)
pivot['Fatality Rate (%)'] = (pivot['y'] / pivot['Total'] * 100).round(2)

pivot.sort_values('Total')

fatal y/n      n    y  Total  Fatality Rate (%)
type
Watercraft    80    0     80               0.00
Provoked     229    3    232               1.29
Unprovoked  1799  166   1965               8.45

In [51]:
# We want to see if there is a correlation between certain species and fatality rates

pivot = pd.pivot_table(
    shark_clean_usa_filtered_df,
    index='species',
    columns='fatal y/n',
    values='year',
    aggfunc='count',
    fill_value=0
)

pivot['Total'] = pivot.sum(axis=1)
# Divide the fatal = y entries by the total amount (rounded to 2 decimal places)
pivot['Fatality Rate (%)'] = (pivot['y'] / pivot['Total'] * 100).round(2)

pivot.sort_values('Total')

fatal y/n           n    y  Total  Fatality Rate (%)
species
Bull Shark         83    5     88               5.68
Tiger Shark       131   16    147              10.88
White Shark       205   25    230              10.87
Other / Unknown  1689  123   1812               6.79

In [52]:
# Checking the final state of the cleaned dataset before additional analysis
# This gives us an overview of column types, non-null counts and memory usage
shark_clean_usa_filtered_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2299 entries, 8 to 7087
Data columns (total 15 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       2299 non-null   object
 1   year       2299 non-null   float64
 2   type       2299 non-null   object
 3   country    2299 non-null   object
 4   state      2299 non-null   object
 5   location   2264 non-null   object
 6   activity   2189 non-null   object
 7   name       2282 non-null   object
 8   sex        2216 non-null   object
 9   age        1636 non-null   object
 10  injury     2296 non-null   object
 11  fatal y/n  2277 non-null   string
 12  time       1548 non-null   object
 13  species    2299 non-null   object
 14  source     2293 non-null   object
dtypes: float64(1), object(13), string(1)
memory usage: 287.4+ KB

## Additional Analysis
**Our Goal:** Analysing other columns then just the MVP to support our hypothesis and narrative with statistical data.

In [53]:
# Looking at and cleaning up the Year column
# We want to check if there are any NaN or null values in year column.

print(shark_clean_usa_filtered_df['year'].isnull().sum())

0

In [54]:
# We want to check what Year values look like
print(shark_clean_usa_filtered_df['year'].value_counts().sort_index())

year
0.0       16
1640.0     1
1642.0     1
1751.0     1
1779.0     1
          ..
2022.0    49
2023.0    45
2024.0    17
2025.0    22
2026.0     3
Name: count, Length: 181, dtype: int64

In [55]:
# Cleaning up Year column
# Step 1 - Dropping rows where year = 0.0 as they are not valid entries
shark_clean_usa_filtered_df = shark_clean_usa_filtered_df[shark_clean_usa_filtered_df['year'] != 0.0]

# Step 2 - Converting year from float to integer now that invalid values are removed
shark_clean_usa_filtered_df['year'] = shark_clean_usa_filtered_df['year'].astype(int)

# Step 3 - Verifying
print(shark_clean_usa_filtered_df['year'].dtype)
print(shark_clean_usa_filtered_df['year'].value_counts().sort_index())

int64
year
1640     1
1642     1
1751     1
1779     1
1780     1
        ..
2022    49
2023    45
2024    17
2025    22
2026     3
Name: count, Length: 180, dtype: int64

In [56]:
# Finding 1 - Total incidents per year
# Focusing on 1900+ where data coverage is reliable
incidents_per_year = shark_clean_usa_filtered_df[
    shark_clean_usa_filtered_df["year"] >= 1900
].groupby("year").size()

print(incidents_per_year.tail(27))

year
2000    49
2001    56
2002    49
2003    50
2004    32
2005    45
2006    50
2007    62
2008    54
2009    35
2010    38
2011    44
2012    61
2013    58
2014    61
2015    66
2016    61
2017    59
2018    37
2019    54
2020    40
2021    53
2022    49
2023    45
2024    17
2025    22
2026     3
dtype: int64

In [57]:
# Finding 1 - Total incidents before 1975 vs total incidents after 1975
# Focusing on the last 100 years: 1925 - 2025

before_1975 = shark_clean_usa_filtered_df[
    (shark_clean_usa_filtered_df["year"] >= 1925) &
    (shark_clean_usa_filtered_df["year"] < 1975)
]

print(len(before_1975))

after_1975 = shark_clean_usa_filtered_df[
    (shark_clean_usa_filtered_df["year"] >= 1975) &
    (shark_clean_usa_filtered_df["year"] < 2025)
]

print(len(after_1975))

334
1727

In [58]:
# Finding 2 - Fatal vs Non-fatal per year
# If sharks were becoming more aggressive, fatality rate should rise over time
# A flat or declining fatality rate supports our narrative
fatal_trend = shark_clean_usa_filtered_df[
    shark_clean_usa_filtered_df['year'] >= 1900
].groupby(['year', 'fatal y/n']).size().reset_index(name= "count")
print(fatal_trend.tail(27))

     year fatal y/n  count
165  2010         y      2
166  2011         n     44
167  2012         n     60
168  2012         y      1
169  2013         n     55
170  2013         y      2
171  2014         n     61
172  2015         n     65
173  2015         y      1
174  2016         n     60
175  2017         n     59
176  2018         n     36
177  2018         y      1
178  2019         n     53
179  2019         y      1
180  2020         n     37
181  2020         y      3
182  2021         n     50
183  2021         y      2
184  2022         n     47
185  2022         y      2
186  2023         n     43
187  2023         y      2
188  2024         n     16
189  2025         n     21
190  2025         y      1
191  2026         n      3

In [59]:
# Looking at the values and cleaning up the column Sex
shark_clean_usa_filtered_df["sex"].value_counts()

sex
M      1819
F       378
 M        1
M         1
lli       1
Name: count, dtype: int64

In [60]:
#Cleaning column Sex
# Step 1 - Filling NaN values with 'Unknown' before stripping
shark_clean_usa_filtered_df['sex'] = shark_clean_usa_filtered_df['sex'].fillna('Unknown')

# Step 2 - Removing whitespace from Sex column
shark_clean_usa_filtered_df['sex'] = shark_clean_usa_filtered_df['sex'].str.strip()

# Step 3 - Keeping only M and F, everything else becomes Unknown
condition_sex = (shark_clean_usa_filtered_df['sex'] != 'M') & (shark_clean_usa_filtered_df['sex'] != 'F')
shark_clean_usa_filtered_df.loc[condition_sex, 'sex'] = 'Unknown'

# Displaying the cleaning result
shark_clean_usa_filtered_df['sex'].value_counts()

sex
M          1821
F           378
Unknown      84
Name: count, dtype: int64

In [61]:
# Finding 1 - Gender vs Fatality Rate
# Do fatal incidents more towards one gender?
gender_fatal_pivot = pd.pivot_table(
    shark_clean_usa_filtered_df[shark_clean_usa_filtered_df['sex'].isin(['M', 'F'])],
    index='sex',
    columns='fatal y/n',
    values='year',
    aggfunc='count',
    fill_value=0
)

gender_fatal_pivot['Total'] = gender_fatal_pivot.sum(axis=1)
gender_fatal_pivot['Fatality Rate (%)'] = (gender_fatal_pivot['y'] / gender_fatal_pivot['Total'] * 100).round(2)

print('Fatality rate by gender:')
print(gender_fatal_pivot)

Fatality rate by gender:
fatal y/n     n    y  Total  Fatality Rate (%)
sex
F           360   14    374               3.74
M          1656  151   1807               8.36

In [62]:
# Finding 2 - Gender vs Provoke
# Do fatal incidents more towards one gender?
gender_type_pivot = pd.pivot_table(
    shark_clean_usa_filtered_df[shark_clean_usa_filtered_df['sex'].isin(['M', 'F'])],
    index='sex',
    columns='type',
    values='year',
    aggfunc='count',
    fill_value=0
)

gender_type_pivot['Total'] = gender_type_pivot.sum(axis=1)
gender_type_pivot['Provoke Rate (%)'] = (gender_type_pivot['Provoked'] / gender_type_pivot['Total'] * 100).round(2)

print('Provoke rate by gender:')
print(gender_type_pivot)

Provoke rate by gender:
type  Provoked  Unprovoked  Watercraft  Total  Provoke Rate (%)
sex
F           13         360           5    378              3.44
M          202        1575          44   1821             11.09

In [63]:
# Looking at the raw activity column

print("Top 20 raw values:")
print()
print(shark_clean_usa_filtered_df["activity"].value_counts().head(20))

Top 20 raw values:

activity
Surfing                    634
Swimming                   332
Fishing                    133
Wading                     116
Standing                    68
Spearfishing                58
Snorkeling                  37
Boogie boarding             31
Bathing                     24
Body boarding               23
Kayaking                    22
Diving                      22
Body surfing                21
Scuba diving                16
Boogie Boarding             13
Swimming                    12
Walking                     10
Free diving                  9
Stand-Up Paddleboarding      9
Playing                      8
Name: count, dtype: int64

In [64]:
# Step 1 - Create a classification function to group activities
# We decided to define a function so the logic is reusable and readable
# The function checks each activity value and assigns it to a category

def group_activity(activity):
    # Cleaning null values first
    if pd.isnull(activity):
        return "Unknown"
    
    activity = activity.lower()
    
    if "surf" in activity:
        return "Surfing"                  
    elif "swim" in activity:
        return "Swimming"
    elif "spear" in activity or "fish" in activity:
        return "Fishing"
    elif "wade" in activity or "wading" in activity or "standing" in activity:
        return "Wading / Standing"
    elif "div" in activity or "snorkel" in activity or "scuba" in activity:
        return "Diving / Snorkeling"
    elif "kayak" in activity or "paddle" in activity or "canoe" in activity or "boat" in activity:
        return "Boating/Paddling"
    elif "boogie" in activity or "body board" in activity:
        return "Bodyboarding"
    else:
        return "Other"

# Step 2 - Applying the function to create a new column called activity_group
shark_clean_usa_filtered_df["activity_group"] = shark_clean_usa_filtered_df["activity"].apply(group_activity)

# Verifying the result
print("Activity group breakdown:")
print(shark_clean_usa_filtered_df["activity_group"].value_counts())

Activity group breakdown:
activity_group
Surfing                784
Swimming               396
Fishing                308
Other                  225
Wading / Standing      200
Diving / Snorkeling    139
Unknown                108
Bodyboarding            70
Boating/Paddling        53
Name: count, dtype: int64

In [65]:
# Step 3 - Displaying the "activity_group" incident count and percentage
# We are showing which activities are most common in shark incidents.

# Finding 1 - High numbers in Surfing and Swimming supports our narrative: "Humans entering shark territory, not sharks hunting humans."

activity_counts = shark_clean_usa_filtered_df["activity_group"].value_counts()
activity_pct = (shark_clean_usa_filtered_df["activity_group"].value_counts(normalize=True) * 100).round(1)

activity_summary = pd.DataFrame({
    "Incidents": activity_counts,
    "Percentage (%)": activity_pct
})

print("Activity breakdown:")
print(activity_summary)

Activity breakdown:
                     Incidents  Percentage (%)
activity_group
Surfing                    784            34.3
Swimming                   396            17.3
Fishing                    308            13.5
Other                      225             9.9
Wading / Standing          200             8.8
Diving / Snorkeling        139             6.1
Unknown                    108             4.7
Bodyboarding                70             3.1
Boating/Paddling            53             2.3

In [66]:
# Finding 2 - Activity vs Fatality Rate 
# The activitiy with highest incidents (Surfing) have the lowest Fatality rate with 1.80%.

activity_pivot = pd.pivot_table(
    shark_clean_usa_filtered_df,
    index="activity_group",
    columns="fatal y/n",
    values="year",
    aggfunc="count",
    fill_value=0
)

activity_pivot["Total"] = activity_pivot.sum(axis=1)
activity_pivot["Fatality Rate (%)"] = (activity_pivot["y"] / activity_pivot["Total"] * 100).round(2)

print("Activity vs Fatality Rate:")
print(activity_pivot.sort_values("Total", ascending=False))

Activity vs Fatality Rate:
fatal y/n              n   y  Total  Fatality Rate (%)
activity_group
Surfing              765  14    779               1.80
Swimming             329  64    393              16.28
Fishing              283  25    308               8.12
Other                190  32    222              14.41
Wading / Standing    195   4    199               2.01
Diving / Snorkeling  124  14    138              10.14
Unknown               94   5     99               5.05
Bodyboarding          64   6     70               8.57
Boating/Paddling      51   2     53               3.77